raft:
  groupMember:
    A: localhost:2333
    B: localhost:2334
    C: localhost:2335
  nodeId: C
  servicePort: 8082
  dataDir: /Users/yuwenbo/IdeaProjects/raft/raft-kvstore/target/C
  mode: group-member